name: Custom Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Custom Test Script
      env:
        BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      run: |
        if [ ! -f "tests/custom_test_script.py" ]; then
          echo "Error: custom_test_script.py not found!"
          exit 1
        fi
        python tests/custom_test_script.py
        if [ $? -ne 0 ]; then
          echo "Tests failed!"
          exit 1
        fi